# Generated by Django 3.2.19 on 2023-08-27 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=50, verbose_name='Название задачи')),
                ('task_description', models.TextField(verbose_name='Описание задачи')),
                ('task_date_start', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения задачи')),
                ('task_date_modified', models.DateTimeField(auto_now=True, verbose_name='Дата обновления задачи')),
                ('task_date_finish', models.DateField(verbose_name='Плановая дата завершения задачи')),
                ('task_status', models.CharField(choices=[('assigned', 'Задача принята'), ('review', 'Задача на ревью'), ('completed', 'Задача завершена'), ('revised', 'Есть замечания')], max_length=20, verbose_name='Текущий статус задачи')),
                ('task_priority', models.IntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий')], default=1, verbose_name='Приоритет задачи')),
                ('employee_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_tasks', to=settings.AUTH_USER_MODEL)),
                ('team_lead_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegated_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
