# Generated by Django 3.2.19 on 2023-08-14 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.TextField(blank=True, help_text='Введите список ваших доступных контактов', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Введите пароль', max_length=255, validators=[django.core.validators.MinValueValidator(4, message='Пароль должен содержать минимум4 символа!'), django.core.validators.MaxValueValidator(30, message='Пароль не может быть длиннее30 символов!')], verbose_name='Пароль'),
        ),
    ]
